version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo $STAGE
      - echo $MY_VAR
      - ./gradlew test
  build:
    commands:
      - ./gradlew shadowJar
artifacts:
  files:
    - build/libs/**/*
